- LED Lighting/Practical_series_2.ir
- Added Practical Series 2 remote.
- https://www.amazon.com/Changing-Daylight-Bulbs-Dimmable-Decoration/dp/B06Y27W7NZ
- Button conventions used : On ( 1 top-left button ), number increase right and bottom, 21 ( bottom-right button )
> - Feature : Added Practical-Series2 remote IR codes

- Audio Receivers/Sony/Sony_Amp.ir
- Blu-Ray/Sony/Sony_Blu_Ray.ir
- TVs/Samsung/Samsung_TV_Full.ir
- TVs/Sony/Sony_Bravia.ir
- TVs/TCL/TCL_32S327.ir
Updated a few files and added a few new ones thanks to OUTsane via Discord
> Additions and updates

- TVs/TCL/TCL_ROKU_US.ir
> Adding TCL Roku TV

- ACs/Toshiba/Toshiba_AC.ir
- Projectors/BenQ/BenQ_W1070.ir
> New remotes (thanks xmutantson!)

- Miscellaneous/Azulle/Azulle_Byte3_Fanless_MiniPC.ir
Now complete (Thanks StephS_escape!)
> Updated Azulle Byte3 Fanless Mini PC

- Streaming Devices/Apple/Apple_TV.ir
> Added Unpair command (thanks TowerOfTerror)

- Miscellaneous/AOC/JXD_021.ir
- Projectors/Anker/NebulaMarsLite.ir
- Anker Nebula Mars Lite projector
- AOC JXD 021 Monitor
> Added 2 new devices (thanks Captain Squishy)

- Miscellaneous/Tomlov/TOMLOV_DM201_Digital_Microscope.ir
> Added TOMLOV DM201 Digital Microscope

- Miscellaneous/AMI/AMI_Jukebox_Full.ir
Found a local restaurant today that allowed me to clone nearly the entire remote.
> Add more complete AMI jukebox remote controller

- Miscellaneous/No-Touch/No-Touch_Thermometer.ir
> Added No-Touch Thermometer (thanks amitchell516!)

- Projectors/Optoma/Optoma_Profomo_L-27-5KEY.ir
- Speakers/Edifier/Edifier_Speakers_RC31A.ir
Edifier Speakers
Optima Projector
> Added 2 more (thanks LMPNS!)

- ACs/Kenmore/Kenmore_AC.ir
- LED_Lighting/Sylvania/Sylvania_24_Button_LED.ir
> 2 new additions (thanks noah!)

- TVs/Manta/Manta_TV.ir
- TVs/Manta/Manta_TV_2.ir
Also made original Manta TV remote ir more pretty
> Added new Manta TV remote

- Speakers/Generic_Unknown_Brand/Dream_Aurora_AC6923.ir
Updated the name of the ir to include model number
> Updated name and added model no

- LED_Lighting/Dasinko/Dasinko_LED.ir
- LED_Lighting/Sylvania/Sylvania_LED.ir
Added Dasinko LED Color Changing Light Bulb and Sylvania LED Remote
> Added 2 LED Light Bulbs

- ACs/Klarstein/Klarstein_Metrobreeze_Miami.ir
- Audio_Receivers/Adastra/Adastra_WA215.ir
- Miscellaneous/GameBoy/Pokemon_Silver_Mystery_Gift.ir
- Miscellaneous/Varytech/Varytech_Fog_Machine_F80B.ir
Added Varytech Fog machine, Pokemon Silver Mystery Gift, Adastra Wall & Ceiling Speaker Set and Klarstein Portable AC
> Multiple Additions

- TVs/Grundig/GRUNDIG.ir
Unknown Grundig TV model from a hotel room in Frankfurt.
> Add Grundig TV remote.

- Heaters/Devola/Devola_ DVPH1200B _Patio_Heater.ir
Adding a patio heater commonly sold in the UK and often found in pub beer gardens. Recorded directly from remote
> Create Devola_ DVPH1200B _Patio_Heater.ir

- LED_Lighting/Nexillumi/Nexillumi_LED.ir
This PR:
* Adds an entry for [Nexillumi](https://www.amazon.com/gp/product/B083XX8BLJ) LED lights
> Add Nexillumi LED controller

- Projectors/Acer/Acer_proj.ir
https://github.com/Ursion-zero/Acer-Projector-IR
> Added Acer projector (thanks 𝐔𝐫𝐬𝐢𝐨𝐧 𝐙𝐞𝐫𝐨!)

- .github/workflows/pr-lint.yaml
now using `pull_request_target` instead of `pull_request`
> ci: check IR files for issues in PRs

- Cable_Boxes/Huawei/Huawei_dn300_mgts(mts).ir
added Huawei_dn300_mgts(mts) remote controler https://cache3.youla.io/files/images/720_720_out/5c/5f/5c5f2a2eaaab2862d173cbef.jpg
> added Huawei_dn300_mgts(mts) remote controler

- SoundBars/Xiaomi/Binnifa_Live1T.ir
- SoundBars/Xiaomi/Binnifa_live1T.ir
- TVs/Samsung/Samsung_UE32F4000AW.ir
added buttons from the UE32F4000 samsung tv remote, tested irl and works
added a full soundbar remote for the binnifa Live1T, tested irl and works
> new buttons for samsung tv and new xiaomi soundbar remote

- LED_Lighting/EAMBRITE/EAMBRITE_100LT_Fairy_Lights.ir
36 button RGB LED fairy lights remote.
> Add EAMBRITE 100LT RGB fairy lights remote

- Touchscreen_Displays/BoxLight/BoxLight_Interactive_Flat_Panel_PROCOLOR653U.ir
Added the BoxLight Interactive Flat Panel ProColor 653U
SpecSheet: https://mimio.boxlight.com/wp-content/uploads/2019/07/ProColor-653U-specsheet.pdf
> Add BoxLight Interactive Flat Panel ProColor 653U

- Projectors/Dell/Dell_tsfm_ir01.ir
I'm unsure what the two squares do on the model I cloned so I labelled them `SquareUp` and `SquareDown`. If anyone knows what it does they can update it with an issue or pull request.
> Addition of Dell TSFM-IR01

- TVs/TCL/TCL_Roku_TV.ir
Added the dedicated channel button for Apple TV, cloned from a stock TCL Roku TV remote
> Added Apple TV button

- Audio_Receivers/Sony/Sony_RM-AAU130_AV.ir
> Add most keys of RM-AAU130

- Cable_Boxes/Claro/Claro_Fujian_Newland_TV_Box.ir
https://github.com/UberGuidoZ/Flipper/issues/448
> Added Claro TV Box (thanks Nash3z!)

- TVs/Daewoo/Daewood_Parsed.ir
Captured from a One for all remote
> Added Daewoo TV remote Unknown model

- Cameras/Sony/ReadMe.md
- Cameras/Sony/Sony.ir
The codes for this came from here: https://github.com/Gordon999/Pi-Sony-A6000-remote/blob/master/Remote2.py
Button names were found here: https://www.sony.com/electronics/support/res/manuals/4570/45701310M.pdf
Tested on my A6400 and confirmed all are working (except for the weird Print button, but I'm assuming it works)
> RMT-DSLR2: Add remaining and hidden functions

- README.md
Updated the naming scheme for the repo according to the new naming scheme layout used.
> Updated naming scheme for organisation on the README

- Air_Purifiers/Rohnson/Rohnson_R-9400.ir
Compatible with air purifier:
- Rohnson R-9400 Fresh Air
> Added air purifier Rohnson R-9400

- DVD_Players/Bose/Bose_3-2-1_Series_1.ir
This is my first pull request. Please let me know if I did anything incorrect. I've got a lot more to contribute. :)
> Added Bose 3-2-1 series 1 remote

- ACs/DeLonghi/Pinguino_EL290HLWKC.ir
I didn't see an IR file for my AC so hopefully this helps someone else at some point :)
I tested all functions on my DeLonghi Pinguino - EL290HLWKC-1A
> Added DeLonghi Pinguino AC Remote 

- Speakers/Edifier/Edifier_R1700BT.ir
Adds codes for Edifier R1700BT speakers (original model)
> Adds codes for Edifier R1700BT speakers (original model)

- CD_Players/Technics/Technics_ST-HD60.ir
https://www.hifiengine.com/manual_library/technics/st-hd60.shtml
> Add Technics ST-HD60
